### ISSUE TITLE
Application stuck on startup

### ISSUE THREAD

**Issue by nobyArdor** [commandprompt/pgmanage#495] opened 2024-09-26 06:12 UTC
PgManage versions  1.1.0 - 1.1.0 is stuck on startup.
Images include
![image](https://github.com/user-attachments/assets/e80a84c9-307c-4bab-8d62-08152fa0cc75)
![image](https://github.com/user-attachments/assets/6e2b493c-20de-47ba-9e83-af31ab0a8872)

**Comment by eug3nix** [comment] 2024-09-27 12:20
Hello, thanks for reporting the issue.
I was able to reproduce and fix the the issue with warning message shown on the screenshot. I am not sure however that it may be the cause or app hanging during startup.
Anyways, here is a 1.1.1 build of pgmanage which does not produce this warning: https://github.com/commandprompt/pgmanage/releases/download/1.1.1-tzfix/pgmanage-1.1.1-tzfix_setup.win64.exe

Can you check if it solves the startup issue?
If not - pgmanage log contents may be helpful to troubleshoot this further, you can find the log file in %USERPROFILE%\.pgmanage\pgmanage-app\pgmanage.log

Cheers!

**Comment by nobyArdor** [comment] 2024-10-02 06:23
As I can suggest issue is not on app side. It may be on server side. I am trying to use pgmanage-server on windows 10 and I can't login with admin or other created user. At the same time there is no anything warning about  "invalid username or password" compared to omnidb-server 3.0.3b.

[pgmanage.log](https://github.com/user-attachments/files/17220538/pgmanage.log)

**Comment by nobyArdor** [comment] 2024-11-14 07:14
Issue can not reproduce in 1.2 version.
Thank all team!

**Comment by eug3nix** [comment] 2024-11-14 09:51
Good to hear that it is resolved for you.
Closing the issue.

**Closed by eug3nix** 2024-11-14 09:51 UTC
